### ISSUE TITLE
layer compatibility error when bitbaking fsl-image-gui for MACHINE=imx8mm-var-dart and DISTRO=fsl-imx-xwayland

### ISSUE THREAD

**Issue by timblaktu** [varigit/var-host-docker-containers#8]
Following the [docker build env instructions](https://variwiki.com/index.php?title=Docker_Build_Environment) with:
- `MACHINE=imx8mm-var-dart`
- `DISTRO=fsl-imx-xwayland`
- using HEAD (148437e07c567fe5e6aaa26fe54932863972d640) of this repo, and `-u 22.04`
- `imx-6.1.36-2.1.0.xml` repo file @ variscite-bsp-platform refs:
    - HEAD of mickledore branch
    - refs/tags/mx8mp-yocto-mickledore-6.1.36_2.1.0-v1.2

I am getting a layer compatibility error when building `fsl-image-gui`:

```
vari@fe84947c33fd:/workdir/build-mickledore-fsl-image-gui$ bitbake fsl-image-gui
ERROR: Layer chromium-browser-layer is not compatible with the core layer which only supports these series: mickledore (layer is compatible with dunfell gatesgarth honister kirkstone hardknott)
```

I interpret this error saying the layers defined in mickledore for `DISTRO=fsl-imx-xwayland` do not include `chromium-browser-layer` nor are compatible with it. What am I missing here? @nsdrude

**Comment by nsdrude** [comment]
@timblaktu please open a ticket in Variscite's support portal so our team can support you: https://www.variscite.com/support/

**Comment by timblaktu** [comment]
Thanks @nsdrude. Does this mean that GitHub Issues and PRs aren't the best way to get help? I've registered for an account at varisciteportal.axosoft.com and am still waiting for the confirmation e-mail.

**Comment by nsdrude** [comment]
@timblaktu yes, the best way for support is using the support portal.

We'll accept PRs, but for support it's best to go through the portal for support

Thanks

**Comment by timblaktu** [comment]
Circling back to this publicly to make the issue resolution transparent to others... 

Using the correct MACHINE value (imx8mp-var-dart), `bitbake fsl-image-gui` proceeds past the layer error.

Aside from obvious cockpit error on my part and making a typo/simple mistake, a big reason for why this happenened IMO was that I am only using containers for build environment, and from what I've seen, there is a great discrepancy between your machine-/release-specific host build instructions in the wiki and the docker build instructions, which appear to only exist in generic (and outdated) form. Please correct this if I'm missing something, i.e. send me a link to instructions for using machine-/release-specific instructions for building using containerized build env instead of host env.

@nsrude What I'd really like is a kas-based build. If anyone knows of any for var-som-imx8mp let me know. Otherwise, my plan is to fork [this mender layer repo](https://github.com/mendersoftware/meta-mender-community/tree/scarthgap/meta-mender-variscite), which is implemented with kas, and add support for the var-som-imx8mp. @nsdrude let me know if you have any leads on this, or have interest in having me collaborate on a kas solution somewhere here in varigit.
